import type { FlexContainer } from './types'
import { stripUids } from './uid'
import { bindTree, collectPlaceholders } from './binding'

export function exportJson(root: FlexContainer, data?: any): string {
  let clean = stripUids(root)
  if (data) clean = bindTree(clean, data)
  return JSON.stringify(clean, null, 2)
}

export function exportMessageJson(root: FlexContainer, altText: string, data?: any): string {
  let clean: any = stripUids(root)
  if (data) clean = bindTree(clean, data)
  return JSON.stringify({ type: 'flex', altText, contents: clean }, null, 2)
}

/**
 * Generate a self-contained JS module: template + bind() so callers can pass
 * their own data object and get a ready-to-send flex message.
 */
export function exportJs(root: FlexContainer, altText: string): string {
  const clean = stripUids(root)
  const placeholders = collectPlaceholders(clean)
  const sample =
    placeholders.length > 0
      ? `\n// ตัวอย่างการใช้งาน:\n// const message = buildFlexMessage({ ${placeholders
          .map((p) => `${JSON.stringify(p)}: '...'`)
          .join(', ')} })\n// await client.pushMessage({ to: USER_ID, messages: [message] })`
      : `\n// ตัวอย่างการใช้งาน:\n// await client.pushMessage({ to: USER_ID, messages: [buildFlexMessage()] })`

  return `// Generated by Flex Message Designer
// ${new Date().toISOString()}

const FLEX_TEMPLATE = ${JSON.stringify(clean, null, 2)}

const ALT_TEXT = ${JSON.stringify(altText)}

/** แทนที่ {{path.to.value}} ทุกจุดใน template ด้วยข้อมูลจริง */
function bind(node, data) {
  if (typeof node === 'string') {
    return node.replace(/\\{\\{\\s*([\\w.\\[\\]-]+)\\s*\\}\\}/g, (m, path) => {
      const value = path
        .replace(/\\[(\\d+)\\]/g, '.$1')
        .split('.')
        .filter(Boolean)
        .reduce((acc, key) => (acc == null ? undefined : acc[key]), data)
      return value === undefined || value === null ? m : String(value)
    })
  }
  if (Array.isArray(node)) return node.map((item) => bind(item, data))
  if (node && typeof node === 'object') {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, bind(v, data)]))
  }
  return node
}

/**
 * สร้าง Flex Message พร้อมส่งผ่าน Messaging API
 * @param {object} [data] ข้อมูลสำหรับ bind เข้า template
 * @param {string} [altText] ข้อความ fallback
 */
export function buildFlexMessage(data = {}, altText = ALT_TEXT) {
  return { type: 'flex', altText: bind(altText, data), contents: bind(FLEX_TEMPLATE, data) }
}
${sample}
`
}

/** curl command for LINE push API (fallback when browser CORS blocks direct send). */
export function curlCommand(root: FlexContainer, altText: string, token: string, to: string, data?: any): string {
  const msg = exportMessageJson(root, altText, data)
  const body = JSON.stringify({ to, messages: [JSON.parse(msg)] })
  return `curl -X POST https://api.line.me/v2/bot/message/push \\
  -H 'Content-Type: application/json' \\
  -H 'Authorization: Bearer ${token || '<CHANNEL_ACCESS_TOKEN>'}' \\
  -d '${body.replace(/'/g, `'\\''`)}'`
}
